services:
  freetakserver:
    image: freetakserver:latest
    pull_policy: build
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /portainer/Files/AppData/Config/fts:/opt/fts/
    ports:
      # DataPackagePort
      - ${DataPackagePort}:8080
      # CoTPort
      - ${CoTPort}:8087
      # SSLCoTPort
      - ${SSLCoTPort}:8089
      # SSLDataPackagePort
      - ${SSLDataPackagePort}:8443
      # FederationPort
      #- 9000:9000
      # APIPort - Don't expose by default
      #- 19023:19023

    environment:
        # The ChangeMe section
        FTS_FED_PASSWORD: ${FTS_FED_PASSWORD}
        FTS_CLIENT_CERT_PASSWORD: ${FTS_CLIENT_CERT_PASSWORD}
        FTS_SECRET_KEY: ${FTS_SECRET_KEY}
        FTS_NODE_ID: ${FTS_NODE_ID}
        FTS_CONNECTION_MESSAGE: ${FTS_CONNECTION_MESSAGE}

        # Networking
        FTS_COT_PORT: ${FTS_COT_PORT}
        FTS_SSLCOT_PORT: ${FTS_SSLCOT_PORT}
        FTS_API_PORT: ${FTS_API_PORT}
        FTS_FED_PORT: ${FTS_FED_PORT}

        FTS_DP_ADDRESS: 127.0.0.1
        FTS_USER_ADDRESS: 127.0.0.1
        FTS_API_ADDRESS: 0.0.0.0

        FTS_ROUTING_PROXY_SUBSCRIBE_PORT: 19030
        FTS_ROUTING_PROXY_SUBSCRIBE_IP: 127.0.0.1

        FTS_ROUTING_PROXY_PUBLISHER_PORT: 19032
        FTS_ROUTING_PROXY_PUBLISHER_IP: 127.0.0.1

        FTS_ROUTING_PROXY_SERVER_PORT: 19031
        FTS_ROUTING_PROXY_SERVER_IP: 127.0.0.1

        FTS_INTEGRATION_MANAGER_PULLER_PORT: 19033 # port to receive worker responses by the integration manager
        FTS_INTEGRATION_MANAGER_PULLER_ADDRESS: 127.0.0.1 # address to receive worker responses by the integration manager

        FTS_INTEGRATION_MANAGER_PUBLISHER_PORT: 19034 # port from which to publish messages by the integration manager
        FTS_INTEGRATION_MANAGER_PUBLISHER_ADDRESS: 127.0.0.1 # address from which to publish messages by the integration manager

        # Misc Settings
        FTS_OPTIMIZE_API: True
        FTS_DATA_RECEPTION_BUFFER: 1024
        FTS_MAX_RECEPTION_TIME: 4
        FTS_NUM_ROUTING_WORKERS: 3
        FTS_COT_TO_DB: True
        # number of milliseconds to wait between each iteration of main loop
        # decreasing will increase CPU usage and server performance
        # increasing will decrease CPU usage and server performance
        FTS_MAINLOOP_DELAY: 100
        FTS_EMERGENCY_RADIUS: 0 # radius of emergency within-which users will receive it
        FTS_LOG_LEVEL: "info"

# volumes:
#   free-tak-core-db: